 <div>
  <div style="float:left;padding:15px;"><a href="index.php">Dashboard</a></div>
  <div style="float:left;padding:15px;"><a href="partsIndex.php">Parts</a></div>
  <div style="float:left;padding:15px;"><a href="appsIndex.php">Applications</a></div>
  <div style="float:left;padding:15px;"><a href="assetsIndex.php">Assets</a></div>
  <div style="float:left;padding:15px;"><a href="reportsIndex.php">Reports</a></div>
  <div style="float:left;padding:15px;"><a href="utilitiesIndex.php">Utilities</a></div>
  <div style="float:left;padding:15px;"><a href="ioIndex.php">Import/Export</a></div>
  <div style="clear:both;"></div>
 </div>
