<?php
include_once(__DIR__.'/mysqlClass.php');
 
class ACESgenerator
{
    
 function createACESdoc($header,$apps,$assets,$options)
 {
     /* options keys
      * 'IncludeCosmeticApps' (boolenan)
      * 'IncludeCosmeticAttributes'  (boolenan)
      * 
      */
     
  $includecosmeticattributes=false; if(array_key_exists('IncludeCosmeticAttributes',$options)){$includecosmeticattributes=$options['IncludeCosmeticAttributes'];}
  $includecosmeticapps=false; if(array_key_exists('IncludeCosmeticApps',$options)){$includecosmeticapps=$options['IncludeCosmeticApps'];}
     
  $doc = new DOMDocument('1.0', 'UTF-8');
  $comments=$doc->createComment("\r\n       File generated by SandPIM - an open-source PIM system\r\n       designed around the ACES and PIES standards.\r\n       Source repo for SandPIM can be found at\r\n       https://github.com/autopartsource/sandpim\r\n");
  $doc->appendChild($comments);
  $root = $doc->createElement('ACES');
  $root = $doc->appendChild($root);
  $root->setAttributeNS('http://www.w3.org/2000/xmlns/' ,'xmlns:xsi' ,'http://www.w3.org/2001/XMLSchema-instance');
  $root->setAttribute('version','4.1');

 // ---------------------- header ------------------------------
  $headerElement =  new DOMElement('Header');
  $root->appendChild($headerElement);
  if(array_key_exists('Company', $header)){$companyElement=new DOMElement('Company',$header['Company']); $headerElement->appendChild($companyElement);}
  if(array_key_exists('SenderName', $header)){$sendernameElement=new DOMElement('SenderName',$header['SenderName']); $headerElement->appendChild($sendernameElement);}
  if(array_key_exists('SenderPhone', $header)){$senderphoneElement=new DOMElement('SenderPhone',$header['SenderPhone']); $headerElement->appendChild($senderphoneElement);}
  if(array_key_exists('TransferDate', $header)){$transferdateElement=new DOMElement('TransferDate',$header['TransferDate']); $headerElement->appendChild($transferdateElement);}
  if(array_key_exists('BrandAAIAID', $header)){$brandAAIAIDElement=new DOMElement('BrandAAIAID',$header['BrandAAIAID']); $headerElement->appendChild($brandAAIAIDElement);}
  if(array_key_exists('DocumentTitle', $header)){$documenttitleElement=new DOMElement('DocumentTitle',$header['DocumentTitle']); $headerElement->appendChild($documenttitleElement);}
  if(array_key_exists('EffectiveDate', $header)){$effectivedateElement=new DOMElement('EffectiveDate',$header['EffectiveDate']); $headerElement->appendChild($effectivedateElement);}
  if(array_key_exists('ApprovedFor', $header)){$approvedforElement=new DOMElement('ApprovedFor'); $headerElement->appendChild($approvedforElement); $countryElement=new DOMElement('Country',$header['ApprovedFor']);  $approvedforElement->appendChild($countryElement);}
  if(array_key_exists('SubmissionType', $header)){$submissiontypeElement=new DOMElement('SubmissionType',$header['SubmissionType']); $headerElement->appendChild($submissiontypeElement);}
  if(array_key_exists('MapperCompany', $header)){$mappercompanyElement=new DOMElement('MapperCompany',$header['MapperCompany']); $headerElement->appendChild($mappercompanyElement);}
  if(array_key_exists('MapperContact', $header)){$mappercontactElement=new DOMElement('MapperContact',$header['MapperContact']); $headerElement->appendChild($mappercontactElement);}
  if(array_key_exists('VcdbVersionDate', $header)){$vcdbversiondateElement=new DOMElement('VcdbVersionDate',$header['VcdbVersionDate']); $headerElement->appendChild($vcdbversiondateElement);}
  if(array_key_exists('QdbVersionDate', $header)){$qdbversiondateElement=new DOMElement('QdbVersionDate',$header['QdbVersionDate']); $headerElement->appendChild($qdbversiondateElement);}
  if(array_key_exists('PcdbVersionDate', $header)){$pcdbversiondateElement=new DOMElement('PcdbVersionDate',$header['PcdbVersionDate']); $headerElement->appendChild($pcdbversiondateElement);}
          
  // --------------------- apps ---------------------------------   
  $appnumber=1;
  foreach($apps as $app)
  {
   if($includecosmeticapps==false && $app['cosmetic']==1){continue;}
  
   $appElement=new DOMElement('App');
   $root->appendChild($appElement);

   $appElement->setAttribute('action', 'A');
   $appElement->setAttribute('id', $appnumber);
   $appElement->setAttribute('ref', $app['id']);
   
   $basevehicleElement=new DOMElement('BaseVehicle');
   $appElement->appendChild($basevehicleElement);
   $basevehicleElement->setAttribute('id', $app['basevehicleid']);
   
   
   // get sorted copy of the attributes
   
   foreach($app['attributes'] as $attribute)
   {
    if($includecosmeticattributes==false && $attribute['cosmetic']==1){continue;}
    
    if($attribute['type']=='vcdb')
    {
     $vcdbElement=new DOMElement($attribute['name']);
     $appElement->appendChild($vcdbElement);
     $vcdbElement->setAttribute('id', $attribute['value']);
    }       
    
    if($attribute['type']=='qdb')
    {
    }       

    if($attribute['type']=='note')
    {
     $noteElement=new DOMElement('Note',$attribute['value']);
     $appElement->appendChild($noteElement);
    }
   }
   
   
   $qtyElement=new DOMElement('Qty',$app['quantityperapp']);
   $appElement->appendChild($qtyElement);
   
   $parttypeElement=new DOMElement('PartType');
   $appElement->appendChild($parttypeElement);
   $parttypeElement->setAttribute('id', $app['parttypeid']);
   
   if(array_key_exists('mfrlabel', $app)){$mfrlabelElement=new DOMElement('MfrLabel',$app['mfrlabel']); $appElement->appendChild($mfrlabelElement);}

   $positionElement=new DOMElement('Position');
   $appElement->appendChild($positionElement);
   $positionElement->setAttribute('id', $app['positionid']);

   $partElement=new DOMElement('Part',$app['partnumber']);
   $appElement->appendChild($partElement);
   
   $appnumber++;
  }
  
  $footerElement=new DOMElement('Footer');
  $root->appendChild($footerElement);
  $recordcountElement=new DOMElement('RecordCount',$appnumber);
  $footerElement->appendChild($recordcountElement);
  return $doc;
 }


 function sortVCdbAttributes($attributes)
 {
     // the ACES XSD requires that VCdb-coded attributes of an app be sequenced in a specific order
     // IMHO this is utter bullshit. This removes the author's abilty to communicate 
     // their intended order of qualifiers to the end consumer.
     // we (this PIM system) very specifically sequeces the attributes tied to an application, and then
     
  if(count($attributes)<=1){return $attributes;}
  $reflist=array('MfrBodyCode'=>1,'BodyNumDoors'=>2,'BodyType'=>3,'DriveType'=>4,'EngineBase'=>5,'EngineBlock'=>6,'EngineBoreStroke'=>7,'EngineDesignation'=>8,'EngineVIN'=>9,'EngineVersion'=>10,'EngineMfr'=>11,'PowerOutput'=>12,'ValvesPerEngine'=>13,'FuelDeliveryType'=>14,'FuelDeliverySubType'=>15,'FuelSystemControlType'=>16,'FuelSystemDesign'=>17,'Aspiration'=>18,'CylinderHeadType'=>19,'FuelType'=>20,'IgnitionSystemType'=>21,'TransmissionMfrCode'=>22,'TransmissionBase'=>23,'TransmissionType'=>24,'TransmissionControlType'=>25,'TransmissionNumSpeeds'=>26,'TransElecControlled'=>27,'TransmissionMfr'=>28,'BedLength'=>29,'BedType'=>30,'WheelBase'=>31,'BrakeSystem'=>32,'FrontBrakeType'=>33,'RearBrakeType'=>34,'BrakeABS'=>35,'FrontSpringType'=>36,'RearSpringType'=>37,'SteeringSystem'=>38,'SteeringType'=>39,'Region'=>40);
  
  $key=array(); $sequence=0;
  foreach($attributes as $elementnumber=>$attribute)
  {
   if($attribute['type']=='vcdb')
   {
    if(array_key_exists($attribute['name'], $reflist))
    {
     $key[$elementnumber]=$reflist[$attribute['name']];
    }
    else
    { //  
     $key[$elementnumber]=$sequence;
    }
   }
   if($attribute['type']=='qdb'){$key[$elementnumber]=100+$sequence;}      
   if($attribute['type']=='note'){$key[$elementnumber]=200+$sequence;}      
   $sequence++;
  }
  return array_multisort($key,'SORT_ASC',$attributes);
 }
 
 
}
?>
